# Generated by Django 4.0 on 2022-01-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_mobile_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name'], 'verbose_name': 'Utilisateur'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('SALES', 'Sales'), ('SUPPORT', 'Support'), ('MANAGEMENT', 'Management'), ('OTHERS', 'Others')], default='OTHERS', max_length=20),
        ),
    ]
